require("globals")
--require('packs')
require("plugs")
require("alphaconfs")
require("mappings")
require("tabsconfs")
require("treeconfs")
require("compl")
require('lspconfs')
require('telescopeconfs')
require('lineconfs')
-- require()
-- require("dash")
